name: Build + Push Docker Image

on:
  workflow_call:
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build + Push Image
        run: |
          docker build -t ghcr.io/danmealwork/ahmed-body-flow-investigations/runner:latest .
          docker push ghcr.io/danmealwork/ahmed-body-flow-investigations/runner:latest